camel-tooling/camel-dap-client-vscode

package.json
- required with newer vsce
- use the 3 languages that should be working soon for Camel debug
adapter
=> Provide activation events

.gitignore, jars/Readme.md, package-lock.json, package.json, postinstall.js, scripts/postinstall.js, src/CamelDebugAdpaterDescriptorFactory.ts
it avoids to push the binaries in source code and it allows to pick
latest version more automatically
=> FUSETOOLS2-1426 - retrieve Debug Adapter Server at build time

.github/workflows/ci.yaml
as we are consuming snapshots (yes, not ideal), it can be useful to
trigger the build manually to ensure latest snapshots is picked up in
tests before a release.
=> FUSETOOLS2-1496 - allow manual build trigger

CHANGELOG.md, README.md, USAGE_DATA.md, src/extension.ts
Currently no test setup is in place. it doesn't make sense to test from
at unit level so not adding tests for now.
requires https://github.com/camel-tooling/camel-debug-adapter/pull/58
=> FUSETOOLS2-1489 - Send telemetry from Camel debug adapter

CHANGELOG.md, README.md
`Debugger` scope
requires https://github.com/camel-tooling/camel-debug-adapter/pull/67
=> FUSETOOLS2-1570 - changelog allow update of variable values in

src/completion/CamelApplicationLauncherTasksCompletionItemProvider.ts
waiting for the Camel application under debug to have the debug jmx
connection ready
=> FUSETOOLS2-1607 - use endsPattern in problemMatcher so that debugger is

CHANGELOG.md
Now, when a breakpoint is set before starting the debugger, the
breakpoint is correctly used. The initializedEvent was sent at the wrong
time before, the debugger was not ready to accept the setBreakpoint
requests as the JMX connection was not ready.
requires https://github.com/camel-tooling/camel-debug-adapter/pull/94
=> FUSETOOLS2-1599 - changelog: support already set breakpoint

.github/workflows/ci.yaml
=> FUSETOOLS2-1566 - upgrade node on Circle CI to version 16

package-lock.json
it will allow a faster build by avoiding the "one time fix up" on each build and ensure to use an up to date format
I only called `npm install` locally to do the migration
=> Migrate package-lock.json from v1 to v2

src/test/ui-test/install.test.ts
VS Code extension tester does not support capturing screenshots in Mocha hooks by default. This change should fix it.
Signed-off-by: Marian Lorinc <mlorinc@redhat.com>
=> FUSETOOLS2-1882 - Use before/after from extester to capture screenshots

README.md, docs/_config.yml, docs/_layouts/default.html, docs/assets/css/style.scss, docs/content/advanced.md, docs/index.md
Signed-off-by: Dominik Jelinek <djelinek@redhat.com>
=> FUSETOOLS2-1926: Migrate VSCode DAP extension readme file to new format

src/ui-test/tests/context.menu.test.ts, src/ui-test/utils.ts
Will work after https://github.com/camel-tooling/camel-dap-client-vscode/pull/389
Relates:
- [FUSETOOLS2-1744](https://issues.redhat.com/browse/FUSETOOLS2-1744)
=> FUSETOOLS2-1744: Provide UI test for commands from context menu

package-lock.json, package.json, src/ui-test/tests/command.palette.test.ts, src/ui-test/tests/context.menu.test.ts, src/ui-test/tests/debugger.test.ts, src/ui-test/tests/editor.actions.test.ts, src/ui-test/tests/install.test.ts, src/ui-test/tests/reload.test.ts, src/ui-test/utils.ts
- Camel Debugger tests -> increase the timeout by 1 minute (based on timeout issues during tests on macOS)
- Jbang commands with automatic reload' ->  increase the timeout by 1 minute  (based on timeout issues during tests on macOS)
- Add timeout for `driver.wait` in function `waitUntilTerminalHasText` (as discussed with @mlorinc here -> https://github.com/camel-tooling/camel-dap-client-vscode/pull/407)
- Add timeout for `driver.wait` with `replaceTextInCodeEditor` (same reason^)
- Delete after/before all/each description -> tests are failed to make screenshot with after/before all/each descriptions. example: [gh_action](https://github.com/camel-tooling/camel-dap-client-vscode/actions/runs/5197356242/jobs/9372997610) , error: `Error: Artifact path is not valid: /Camel file editor …
=> Add minor updates in ui-tests 

package.json
removing `yml` because it is not properly working for camel run with jbang and in our extensions we are basically supporting `.yaml/.camel.yaml`
=> FUSETOOLS2-2074: Unify condition to show or not the commands and contextual menus for "simple" run and "debug and run"

src/ui-test/resources/demo route.camel.yaml, src/ui-test/tests/camel.settings.test.ts, src/ui-test/tests/command.palette.test.ts, src/ui-test/tests/context.menu.test.ts, src/ui-test/tests/debugger.test.ts, src/ui-test/tests/editor.actions.test.ts, src/ui-test/tests/reload.test.ts, src/ui-test/utils.ts
Hi, added the test according to the issue https://issues.redhat.com/browse/FUSETOOLS2-2111
Camel Debugger tests
✔ Toogle breakpoint on log line (14) (17249ms)
✔ Update Body value with Camel debugger (15595ms)
✔ Update Header value with Camel debugger (15216ms)
✔ Click on Continue button, and check updated message (14352ms)
✔ Untoogle breakpoint on log line (14) (511ms)
Extra:
- Changed template file (header added)
- Changed common variables to reflect file changes
- Added test with continue button click to see logout of next iteration in the debugger
=> FUSETOOLS2-2111: Add Set Header test

package.json
Looking for the better place to execute eslint. Currently the linter was skipped and only executed as part of `npm test`
=> Move eslint execution to compile script

.github/workflows/insider.yaml, .github/workflows/main.yaml, src/ui-test/resources/demo route.camel.yaml, src/ui-test/tests/camel.settings.test.ts, src/ui-test/tests/command.palette.test.ts, src/ui-test/tests/context.menu.test.ts, src/ui-test/tests/debugger.test.ts, src/ui-test/tests/editor.actions.test.ts, src/ui-test/tests/reload.test.ts, src/ui-test/utils.ts
Hi, added the test according to the issue https://issues.redhat.com/browse/FUSETOOLS2-2154
Camel Debugger tests
✔ Toggle breakpoint on log line (17) (40658ms)
✔ Update Body value with Camel debugger (15664ms)
✔ Update Header value with Camel debugger (13338ms)
✔ Update Exchange property value with Camel debugger (3673ms)
✔ Click on Continue button, and check updated message (13461ms)
✔ Untoggle breakpoint on log line (17) (448ms)
Extra:
- Changed template file (property added)
- Changed common variables to reflect file changes
- Separate reload test to three test for each changed element (body, header, property)
**Question/Possible Issue:**
I faced a lack of logs in `camel.impl.debugger.BacklogDebugger`
Example for Message/Body value:
2023-07-25 12:44:12.944  INFO 47051 --- …
=> FUSETOOLS2-2154: Add Set Exchange property test

src/ui-test/tests/command.palette.test.ts, src/ui-test/tests/context.menu.test.ts, src/ui-test/tests/debugger.test.ts
Based on the latest test results (windows) need to adjust timeouts for debug actions from 60s to 120s with interval from 2s to 4s
Result: Increased stability of debug tests
Typical error:
1) JBang commands execution through command palette
Execute command 'Run Camel Application with JBang and Debug' in command palette:
TimeoutError: Wait timed out after 65238ms
at D:\a\camel-dap-client-vscode\camel-dap-client-vscode\node_modules\selenium-webdriver\lib\webdriver.js:929:17
=> Adjust timeouts based on test results

src/extension.ts, src/test/runTest.ts, src/test/suite/completion.task.test.ts, src/ui-test/uitest_runner.ts
Init issues Relate to #461:
**Fixed with added async/await**
~~/home/runner/work/camel-dap-client-vscode/camel-dap-client-vscode/src/extension.ts
Warning: 40:2 warning Promises must be awaited, end with a call to .catch, end with a call to .then with a rejection handler or be explicitly marked as ignored with the void operator @typescript-eslint/no-floating-promises
Warning: 72:8 warning Promises must be awaited, end with a call to .catch, end with a call to .then with a rejection handler or be explicitly marked as ignored with the void operator @typescript-eslint/no-floating-promises
Warning: 92:2 warning Promises must be awaited, end with a call to .catch, end with a call to .then with a rejection handler or be explicitly marked as ignored with the void operator …
=> Fix floating promises warings 

package-lock.json, package.json, src/ui-test/tests/debugger.test.ts, src/ui-test/utils.ts
I have accidentally closed PR #463, so it is the replacement for it
With bump I have added:
- debugger test refactoring with new extester features 
- added disable/enable breakpoint -> here was found a bug https://issues.redhat.com/browse/FUSETOOLS2-2162, so tests are skipped for now
=> Bump vscode-uitests-tooling from 4.0.3 to 4.0.5

src/task/CamelJBangTaskProvider.ts, src/test/suite/camel.jbang.version.settings.test.ts, src/test/suite/camel.version.settings.test.ts, src/test/suite/util.ts
The main problem is that `cmd` support a single quotation and if `cmd` was chosen as the default shell for VS Code, dap commands will fail.
fix #467 
Commands will be (Run):
- **WINDOWS-CMD**: jbang "-Dcamel.jbang.version=3.21.0" camel@apache/camel run "demo route.camel.yaml" --dev --logging-level=info 
- **WINDOWS-PS**/**MACOS**/**Linux**: jbang '-Dcamel.jbang.version=3.21.0' camel@apache/camel run 'demo route.camel.yaml' --dev --logging-level=info
The actual change in command structure will always add appropriate quoting (single/double) to maven pipeline arguments and always add appropriate quoting to file argument in case space in it.
=> Fix Command Quotation issue

package-lock.json, package.json, src/ui-test/tests/01_install.test.ts, src/ui-test/tests/codelens.test.ts, src/ui-test/uitest_runner.ts, src/ui-test/utils.ts, src/ui-test/variables.ts
Add test to check whether it is possible to debug yaml file using debug codelense. It verifies that debugger is launched and the program pauses at the selected breakpoints.
Please note, as part of this PR I have experimented with variables structure, because I believe single utils.ts is not optimal as long term solution. Also, I have marked a few candidates to vscode-uitestest-tooling and I would value your feedback regarding those proposed functions.
=> FUSETOOLS2-1743 Add JBang lense debug test

.github/workflows/insider.yaml, .github/workflows/main.yaml, Jenkinsfile
On Jenkins CI host, the ipV6 is now deactivated.
otherwise somewhere between the host and the npmjs website ipV6, a layer is not handling it correctly.
=> FUSETOOLS2-2176 - use Node 18 for build

src/ui-test/tests/01_install.test.ts
I reworked the marketplace test a bit.
If flakiness still exists its rate should be  <0.5% now (was 5%), so that test now looks VERY stable.
Also, I deleted tests on the command line commands because it is redundant with other tests.
BTW here is a challenge for `extester` and `vscode-uitests-tooling` with marketplace object.
It is somehow updated in dom regularly and the extester loses control under it and ExtensionsViewItem, that leads to `StaleElementReferenceError`
So, the solution was if during the test we face `StaleElementReferenceError` => get new objects for marketplace and ExtensionsViewItem 
(And it is more stable than solutions in `camelk` and `lsp` so can be used there as well)
[FUSETOOLS2-2149](https://issues.redhat.com/browse/FUSETOOLS2-2149)
=> FUSETOOLS2-2149: Update UI Install test

src/ui-test/utils.ts
It was an old "Internal error" detector that allowed previously catch that error but for now seems it is not only useless but also leads to HUGE flakiness on macOS. In case of  "Internal error",  there still will be catch in that test
https://issues.redhat.com/browse/FUSETOOLS2-2236
=> FUSETOOLS2-2236: Fix Debugger test flakiness

.github/workflows/insider.yaml, .github/workflows/main.yaml
Will help with some after all loops issues (https://github.com/camel-tooling/camel-dap-client-vscode/pull/521)
UI test cancelled: 
UI test success:
=> FUSETOOLS2-2242: Collect ui-tests screenshoots and logs when cancelled

.github/workflows/main.yaml
The Debug Adapter server is added as a child of another top level component
instead of the VS Code extension itself but not found another way to do it in SBOM. It is not the nicest but it improves a lot the analysis anyway and should be sufficient for a long time.
note: it might be interesting to move the version number with a -dev suffix to better read and analyze the results
=> FUSETOOLS2-2206 - Include Debug Adapter Server in Model hierarchy

package-lock.json, package.json, src/ui-test/resources/tasks-examples/01_launch_camel_debug_profile.json, src/ui-test/resources/tasks-examples/02_run_jbang_w_camel_debug.json, src/ui-test/resources/tasks-examples/03_start_mvn_camel_debug_goal.json, src/ui-test/resources/tasks-examples/04_start_mvn_quarkus_dev_debug_profile.json, src/ui-test/resources/tasks-examples/05_start_mvn_camel_debug_profile.json, src/ui-test/resources/tasks.json, src/ui-test/tests/tasks.json.autocompletion.test.ts, src/ui-test/utils.ts, src/ui-test/variables.ts, tsconfig.json
Compiler changed to ES2022 to add support for .at() function on String[] to allow test parameterization.  
=> FUSETOOLS2-2065: Provide tests for completion inside tasks.json

.github/workflows/insider.yaml, .github/workflows/main.yaml
Currently we are using "macos-latest" label which points to macOS 12 were is the default system JDK = Java 8.
It would be better to switch for some time to using label "macos-13" which brings benefits of
1. testing with newer macOS
2. default system JDK is Java 17
=> FUSETOOLS2-2267: Switch GitHub actions jobs to use directly 'macos-13' runner label

.github/workflows/insider.yaml, .github/workflows/main.yaml, src/ui-test/variables.ts
Enforce same default storage setup as ExTester - see https://github.com/redhat-developer/vscode-extension-tester/wiki/Test-Setup#useful-env-variables
=> Use same default UI tests storage as vscode-extension-tester

src/ui-test/tests/debugger.test.ts
Due to new Variables tree item, the header section is sometimes not completely visible. Consequently, collapsing a section allows to let the full variable section visible.
=> Collapse a section to have UI test passing

.github/workflows/main.yaml
With new feature of preference, some tests are failing with 1.82.3 on CI. Updating to more recent version as we want to ensure only 2 versions at least and only best effort for more
=> Increase minimal VS Code version to test with

package-lock.json, package.json
Brings latest release of ExTester v8.1.0
=> Bump vscode-uitests-tooling from 4.1.0 to 4.1.1

CHANGELOG.md, src/extension.ts
unfortunately I did not find out way how to easily grey out (disable) buttons when some conditions are not met.. so I have provided notification which is displayed when some action (eg run button click) is trying to execute jbang command with missing opened folder/workspace
=> FUSETOOLS2-2388: Provide guidance when no folder is opened and commands cannot work

src/task/CamelJBangTaskProvider.ts, src/test/suite/camel.extra.launch.parameter.settings.test.ts
=> Avoid unexpected white spaces inserting into jbang command arguments

CHANGELOG.md, scripts/postinstall.js
requires https://github.com/camel-tooling/camel-debug-adapter/pull/344 and publish on Maven repository
=> Use released Camel Debug Adapter 1.2.0

.github/workflows/main.yaml, src/ui-test/utils.ts
it will improve test stability.
It remains that we are testing 2 versions back in time to let users time to upgrade.
No changing the minimal engine version as in theory it should continue to work.
=> Increase minimal version tested to 1.90.2

.github/workflows/main.yaml, CHANGELOG.md, package.json, src/ui-test/tests/camel.settings.test.ts
I feel the best place to test it is at global level with the full extension pack available as there can be movign part in several places. So I reported:  https://issues.redhat.com/browse/FUSETOOLS2-2497 . What do you think?
=> FUSETOOLS2-2503 - Include *.xsl files by default when running with Camel JBang

CHANGELOG.md, src/task/CamelJBangTaskProvider.ts
single Camel route actions
it allows to have extra parameters still relevant when the Camel route is inside a subfolder (such as the *.xsl files or kamelets)
=> Use containing folder directory as current working directory in task for

.gitignore, CHANGELOG.md, src/task/CamelJBangTaskProvider.ts, src/test/suite/camel.extra.launch.parameter.settings.test.ts
for example in zsh shell the *.xsl as jbang argument is not working, it needs to be passed with single quotes
=> fix: some parameters in shell execution can make problems which leads to task failure

src/ui-test/tests/codelens.test.ts
sometimes, the codelens elements are recomputed between the time we find
the element and the time we try to click on it. it leads to stale
reference error.
Applied a workaround which is consists in retrying one time in case it
happens. It was successful 3 times in row on CI for all jobs (last
builds without the workaround, it was always failing at least one of the
matrix job)
=> FUSETOOLS2-2605: workaround for codelenses that could be recomputed

docs/index.md
=> FUSETOOLS2-2516 - Provide workaround in doc to use Camel debugger with

CHANGELOG.md, src/task/CamelJBangTaskProvider.ts
```
2025-01-21 14:54:53.619 [info] ExtensionService#_doActivateExtension redhat.vscode-debug-adapter-apache-camel, startup: false, activationEvent: 'onStartupFinished', root cause: redhat.vscode-kaoto
2025-01-21 14:54:59.972 [error] TypeError: Cannot read properties of undefined (reading '0')
at CamelJBangTaskProvider.handleMissingXslFiles (d:\a\vscode-kaoto\vscode-kaoto\.vscode-test\extensions\redhat.vscode-debug-adapter-apache-camel-1.5.0\out\task\CamelJBangTaskProvider.js:227:81)
at CamelJBangTaskProvider.getExtraLaunchParameter (d:\a\vscode-kaoto\vscode-kaoto\.vscode-test\extensions\redhat.vscode-debug-adapter-apache-camel-1.5.0\out\task\CamelJBangTaskProvider.js:216:25)
at CamelJBangTaskProvider.createRunWithDebugTask (d:\a\vscode-kaoto\vscode-kaoto\.vscode-test\extensions\redhat.vsco …
```
=> Avoid potential activation failure when no workspace is opened

.vscode/launch.json, package.json, src/test/runTest.ts, src/test/suite/camel.extra.launch.parameter.settings.test.ts, src/test/suite/util.ts, src/ui-test/uitest_runner.ts, tsconfig.json
- Adds launch configuration to start ui-tests.
- Adds launch configuration to attach to a running node process
(usefull when launching from the terminal with VSCode's auto attach
feature enabled).
- Adds better handling of exceptions in the ui-test runner. The
runner will print the exception message and stack trace to the
console.
Signed-off-by: Marcelo Henrique Diniz de Araujo <mdinizde@redhat.com>
=> chore: add launch configurations to debug ui-tests

.github/workflows/deploy.yaml, CHANGELOG.md, docs/content/kubernetes-deploy.md, package.json, src/ui-test/resources/vscode-settings-minikube.json, src/ui-test/tests/deploy.kubernetes.run.test.ts
By default, Camel Jbang is now using Jib and not Docker and providing a multi-arch platform and the way to produce images are no more the same consequently:
* a specific registry must be configured. We found only using Docker to make it working with Minikube.
* qemu is required for the multi-arch with Docker
* resgitry-alias is required because vs code tasks cannot escape and interpret correctly the env command of the registry setup
* can get back to use --dev mode (was removed with 4.8.1 as it wasn't working anymore)
* add --verbose to have more information directly in the shell as it was before 4.8
* 
Note: I abandoned to search why the previous way of doing the deploy/delete was failing with this version, moved directly to use the --dev
=> Use Camel 4.10.2 by default for Camel JBang

.github/workflows/camel_version.yaml
4.4.5 has reached End of Life already. And 4.8.x is an LTS. 4.10 is currently tested with default version used
=> Test with 4.8.5 instead of 4.4.5

src/ui-test/uitest_runner.ts
I have noticed that the all UI tests are executed all the time even if I call only one specific file to be run
=> fix: prevent uitest_runner.js to be executed either when only some specific test is called

CHANGELOG.md, package.json
Camel 4.11 has introduced `--disable-auto` parameter without checking if the cluster-type has been already set or not.
The automatic detection does not work if connected user cannot list resource "clusterversions" in API group "config.openshift.io" at the cluster scope.
Other better ways that could be done later on:
* remove automatically the --disable-auto when detecting that the version is prior to 4.11
* forget about 4.11 and improve handling these parameters in Camel JBang
=> Fix deploy on OpenShift by default on restricted environments

.github/workflows/camel_version.yaml, .github/workflows/deploy.yaml, .github/workflows/insider.yaml, .github/workflows/main.yaml
last VS Code extension tester update changed the place the screenshots are stored, there is an extra folder based on a timestamp
=> Update path to UI test screenshots on CI

package.json
the modification in Camel was backported from 4.11 to 4.10.4 so changing the message to be more precise
=> FUSETOOLS2-2583 - update description on --disable-auto option

.github/workflows/main.yaml, CHANGELOG.md, package-lock.json, package.json
to keep it compatible with latest OpenShift Dev Spaces. In theory, using Node 22 is not a problem
=> Switch back minimal version to 1.100
