.github/workflows/ci.yaml

Use latest setup action java (v2)

---

.github/workflows/sonar.yaml
sonar-project.properties

Sonar analysis

---

.github/workflows/sonar.yaml

Use main branch and not master

---

Jenkinsfile

it allows to publish binaries (snapshots and stables) on
download.jboss.org ad to publish on Microsoft Marketplace and Open VSX
marketplace using the Red Hat publisher

Provide Jenkinsfile

---

package-lock.json
package.json
src/test/suite/index.ts

use a Mocha Jenkins reporter to have test report generated and found by

---

CHANGELOG.md
README.md

FUSETOOLS2-1497 - Provide more specific changelog/readme for first

---

CHANGELOG.md
package.json

FUSETOOLS2-1503 - Provide keywords to improve discoverability in

---

CHANGELOG.md
LICENSE.txt

FUSETOOLS2-1512 - Provide license file

---

README.md

FUSETOOLS2-1498 - provide a sonar badge on readme

---

.github/dependabot.yml

FUSETOOLS2-1500 - configure dependabot

---

CHANGELOG.md
README.md

given that there is now a test covering the most common scenario on
server side and it is tested manually in VS Code.
it will need a test too but it requires/will be covered by
https://issues.redhat.com/browse/FUSETOOLS2-1515 )

FUSETOOLS2-1439 - add Yaml as supported in changelog and readme

---

CHANGELOG.md
README.md

requires https://github.com/camel-tooling/camel-dap-client-vscode/pull/35

1438 xml as supported

---

scripts/postinstall.js

Use released version of server 0.0.1

---

CHANGELOG.md
README.md

requires https://github.com/camel-tooling/camel-debug-adapter/pull/68

FUSETOOLS2-1571 - changelog - allow update of message Body value

---

CHANGELOG.md
README.md

requires https://github.com/camel-tooling/camel-debug-adapter/pull/70

FUSETOOLS2-1572 - changelog - allow update of message header value

---

CHANGELOG.md
README.md

type
requires https://github.com/camel-tooling/camel-debug-adapter/pull/73

FUSETOOLS2-1573 - Support update of Exchange property values when string

---

Jenkinsfile

FUSETOOLS2-1587 - fix upload to download.jboss.org - with correct flag

---

scripts/postinstall.js

Use tagged server 0.1.0 to do a release

---

CHANGELOG.md
package-lock.json
package.json
scripts/postinstall.js

Prepare next development iteration 0.2.0

---

scripts/postinstall.js

Fix download of server

---

Contributing.md

Provide contributing guide

---

CHANGELOG.md
package-lock.json
package.json
scripts/postinstall.js

Fix configuration attributes of debug launch configuration in a 0.1.1

---

CHANGELOG.md
package-lock.json
package.json
scripts/postinstall.js

Prepare next developmet iteration 0.2.0 (again)

---

package.json
src/completion/CamelApplicationLauncherTasksCompletionItemProvider.ts

FUSETOOLS2-1611 - provide probleMatchers to simplify configuration of

---

CHANGELOG.md
scripts/postinstall.js

Use released 0.2.0 version of debug adapter

---

CHANGELOG.md
package-lock.json
package.json
scripts/postinstall.js

Prepare next development iteration 0.3.0 with upgraded server

---

README.md
package.json
src/task/CamelJBangTaskProvider.ts

jbang is the command 
JBang is the name of the project
Jbang is a mistake ;)
thanks!

Jbang -> JBang

---

CHANGELOG.md
README.md
package.json
src/extension.ts

heuristic is not very good (all xml, java, yaml and yml files) but not
worse than for Camel K.

FUSETOOLS2-1312 - Debug with JBang on right-click in File explorer

---

CHANGELOG.md
README.md
src/completion/CamelApplicationLauncherTasksCompletionItemProvider.ts

FUSETOOLS2-1623 - completion for task to launch with Camel Quarkus

---

CHANGELOG.md
README.md

requires https://github.com/camel-tooling/camel-debug-adapter/pull/96/

FUSETOOLS2-1436 - conditional breakpoint

---

CHANGELOG.md
package-lock.json
package.json
scripts/postinstall.js

Prepare next iteration development 0.4.0

---

CHANGELOG.md
src/completion/CamelApplicationLauncherTasksCompletionItemProvider.ts

FUSETOOLS2-1665 - provide snippet completion for camel:debug

---

.github/workflows/ci.yaml

Test on 3 OSes

---

CHANGELOG.md

requires https://github.com/camel-tooling/camel-debug-adapter/pull/136

FUSETOOLS2-1819 - changelog fix regression on updating variable values

---

CHANGELOG.md
README.md
src/codelenses/CamelJBangCodelens.ts
src/test/suite/codelenses/CamelJBangCodelens.test.ts

FUSETOOLS2-1814 - codelens naming improvement

---

CHANGELOG.md
package-lock.json
package.json
scripts/postinstall.js

Prepare next development iteration 0.6.0 with Debug Adapter server

---

CHANGELOG.md

one, more details when unverified
requires https://github.com/camel-tooling/camel-debug-adapter/pull/138

FUSETOOLS2-1670 - Improve tooltip for breakpoints: removed for verified

---

.github/workflows/ci.yaml
.gitignore
.vscodeignore
package-lock.json
package.json
src/test/suite/index.ts
src/test/ui-test/install.test.ts
src/test/ui-test/launcher.ts
tsconfig.json

This PR adds new ui tests which verify marketplace data and contributed commands. The tests are written in different way than usual. Every test uses its own [state machine](https://github.com/mlorinc/selenium-state-machine) which controls test execution. Test is further split into states and transitions between states.
The biggest advantage of the state machines is ability to return to any state. With this feature it is possible to recover from tricky errors such as _StaleElementReferenceError_.  In order to fix the stale error in the state machine one just needs to add new transitions between states. However this is automated by the linked library. On the other hands fixing the stale error in imperative code usually involves rewriting code segments and reorganising loops/method calls. …

FUSETOOLS2-1628 - Provide common extension UI test for DAP extension

---

.github/workflows/main.yaml

Add 1.67.2 vs code version to main workflow matrix as discussed with @apupier

Add 1.67.2 code to main workflow

---

CHANGELOG.md
package.json
src/ui-test/resources/demo route.camel.yaml
src/ui-test/tests/editor.actions.test.ts

FUSETOOLS2-1970: Provide Action to start and debug with JBang for Camel files in VS Code

---

CHANGELOG.md
README.md
package.json
src/extension.ts
src/task/CamelJBangTaskProvider.ts
src/ui-test/tests/install.test.ts

FUSETOOLS2-2013: Provide command to run camel file with JBang

---

package.json

FUSETOOLS2-2025: Command 'Start and Debug' is available even Camel file is not opened

---

CHANGELOG.md
package.json
src/ui-test/tests/editor.actions.test.ts

FUSETOOLS2-2014: Provide Action to Run with Camel JBang

---

scripts/postinstall.js

note: changelog was already updated

Use released version 0.6.0 of the server

---

CHANGELOG.md
README.md
docs/index.md
src/codelenses/CamelJBangCodelens.ts
src/extension.ts
src/test/runTest.ts
src/test/suite/codelenses/CamelJBangCodelens.test.ts

FUSETOOLS2-2015: Provide codelens to run integration with Camel JBang

---

CHANGELOG.md
README.md
package.json
src/ui-test/tests/context.menu.test.ts

FUSETOOLS2-2070: Provide Context Menu to Run with Camel JBang

---

CHANGELOG.md
package.json
src/extension.ts
src/task/CamelJBangTaskProvider.ts
src/test/runTest.ts
src/test/suite/camel.jbang.version.test.ts

FUSETOOLS2-2043: Provide settings in VS Code for Camel JBang version

---

src/ui-test/tests/command.palette.test.ts
src/ui-test/tests/editor.actions.test.ts
src/ui-test/utils.ts

Relates:
- [FUSETOOLS2-2018](https://issues.redhat.com/browse/FUSETOOLS2-2018)

FUSETOOLS2-2018: Provide UI test for the Run Camel application

---

src/extension.ts

Checked with VS Code dev mode stream:
https://analytics.amplitude.com/redhat/chart/cn34vwek
and report is ready fo rwhen there will be a release https://analytics.amplitude.com/redhat/chart/h6c4o4wj/edit/3zs9ytfu

FUSETOOLS2-2084 - Provide telemetry for `Run Camel application with JBang`

---

package-lock.json
package.json
src/ui-test/tests/reload.test.ts
src/ui-test/utils.ts

Related:
https://issues.redhat.com/browse/FUSETOOLS2-2075

FUSETOOLS2-2075: UI test Jbang commands with automatic reload

---

src/ui-test/tests/debugger.test.ts

Related: https://issues.redhat.com/browse/FUSETOOLS2-1822
Test result:

FUSETOOLS2-1822: UI test for value update with debugger

---

CHANGELOG.md

requires https://github.com/camel-tooling/camel-debug-adapter/pull/226

FUSETOOLS2-2142 - changelog redirect Step In and Step Out to next step

---

CHANGELOG.md
README.md

FUSETOOLS2-2132 - mention Java 11 deprecation and Java 17 soon becoming

---

CHANGELOG.md
package.json
src/task/CamelJBangTaskProvider.ts
src/test/suite/maven.repository.settings.test.ts
src/ui-test/tests/camel.settings.test.ts
src/ui-test/utils.ts

Depends on #420 
EDIT:
- #471 needs to be merged first

FUSETOOLS2-2051: Provide Red Hat Maven repository with Jbang by default when version contains redhat

---

CHANGELOG.md

FUSETOOLS2-2051 - place settings for Maven repository to correct version

---

src/ui-test/tests/codelens.test.ts

https://issues.redhat.com/browse/FUSETOOLS2-2151

FUSETOOLS2-2151 Add JBang lense run test

---

.github/workflows/main.yaml
scripts/postinstall.js

- Download sbom corresponding to embedded Camel Debug Adapter Server
- Merge it with the one of the VS Code application
- Store it on GitHub workflow for now

FUSETOOLS2-2202 - Include Camel DAP SBom

---

src/ui-test/uitest_runner.ts

Just replace extester import with tooling

Delete last extester import

---

.github/workflows/main.yaml

upload-artifact v4 is less permissive

Fix main branch - upload sbom a single time

---

Jenkinsfile

- Add step to generate sbom using cyclonedx-cli and cyclonedx-npm
- Add cyclonedx to the install requirements step

FUSETOOLS2-2276: Generate sbom for VS Code Extensions for DAP for Camel also on Jenkins

---

CHANGELOG.md
README.md
package.json
src/task/CamelJBangTaskProvider.ts
src/test/suite/camel.extra.launch.parameter.settings.test.ts
src/ui-test/tests/camel.settings.test.ts
src/ui-test/utils.ts

UI tests to be handled via
https://issues.redhat.com/browse/FUSETOOLS2-2362 as there is a missing feature in VS COde extension tester for now

Fusetools 2314 add preference for extra parameters to run and debug

---

src/test/suite/camel.extra.launch.parameter.settings.test.ts
src/ui-test/tests/camel.settings.test.ts

Adds tests specific to manipulating array settings which is the type for
the "extra launch parameter" setting.
Signed-off-by: Marcelo Henrique Diniz de Araujo <mdinizde@redhat.com>

FUSETOOLS-2362: Adds UI tests for extra parameters when lauching with JBang

---

Jenkinsfile

it avoids having the binary inside the vsix
similar to https://github.com/camel-tooling/camel-lsp-client-vscode/pull/1783

FUSETOOLS2-2400 - install the cyclonedx after packaging the vsix

---

.github/workflows/coverage.yaml
.gitignore
.vscodeignore
package.json
src/ui-test/uitest_runner.ts
tsconfig.json

FUSETOOLS2-2402: Setup code coverage

---

README.md
docs/index.md

requires https://github.com/camel-tooling/camel-debug-adapter/pull/333

FUSETOOLS2-2407 - readme and changelog for pause/resume route definition

---

src/completion/CamelApplicationLauncherTasksCompletionItemProvider.ts
src/ui-test/resources/tasks-examples/04_start_mvn_quarkus_dev_debug_profile.json
src/ui-test/resources/tasks-examples/06_build_native_camel_quarkus_debug.json

2 options are mandatory for quite some time

FUSETOOLS2-2421 - Add extra configuration for Camel Quarkus to debug

---

CHANGELOG.md
README.md
docs/index.md

requires https://github.com/camel-tooling/camel-debug-adapter/pull/342

FUSETOOLS2-1428 - changelog and doc for remote debug through http

---

.eslintrc.json
package-lock.json
package.json
src/test/runTest.ts

- Avoid use of require()
- Use chai friendly eslint rule for unused expressions

Fix eslint issues

---

package.json
src/ui-test/resources/actions/route1.camel.yaml
src/ui-test/resources/actions/route2.camel.yaml
src/ui-test/resources/actions/top/top-route1.camel.yaml
src/ui-test/resources/actions/top/top-route2.camel.yaml
src/ui-test/tests/actions.requirements.test.ts
src/ui-test/tests/editor.actions.test.ts
src/ui-test/variables.ts

FUSETOOLS2-2399: ui-test: Provide submenu quick action button to run with all elements

FUSETOOLS2-2399: ui-test: Provide submenu quick action button to run with all elements

---

CHANGELOG.md
package-lock.json
package.json
scripts/postinstall.js

requires https://github.com/camel-tooling/camel-debug-adapter/pull/382

Prepare next development iteration 1.5.0

---

package-lock.json
package.json
src/ui-test/tests/01_install.test.ts
src/ui-test/tests/actions.requirements.test.ts
src/ui-test/tests/camel.settings.test.ts
src/ui-test/tests/codelens.test.ts
src/ui-test/tests/command.palette.test.ts
src/ui-test/tests/context.menu.test.ts
src/ui-test/tests/debugger.test.ts
src/ui-test/tests/deploy.kubernetes.run.test.ts
src/ui-test/tests/editor.actions.test.ts
src/ui-test/tests/pause.test.ts
src/ui-test/tests/reload.test.ts
src/ui-test/tests/tasks.json.autocompletion.test.ts
src/ui-test/tests/tasks.json.launch.test.ts
src/ui-test/tests/variables.test.ts
src/ui-test/uitest_runner.ts
src/ui-test/utils.ts

remove vscode-uitests-tooling dependency

chore(deps-dev): depend directly only on vscode-extension-tester package

---

.github/workflows/camel_version.yaml
.github/workflows/coverage.yaml
.github/workflows/deploy.yaml
.github/workflows/insider.yaml
.github/workflows/main.yaml

there are issues with Ubuntu 24 which is the new default version
reported https://issues.redhat.com/browse/FUSETOOLS2-2519 to upgrade to latest Ubuntu later

Stay on Ubuntu 22 for test on CI for now

---

.github/workflows/camel_version.yaml

it corresponds to release number 4.4.4

Upgrade to latest 4.4 productized version used in test

---

.github/workflows/camel_version.yaml

it wasn't working with 4.8.0 but the fix made it to 4.8.3 simplified test matrix as there are too many jobs currently and CI not stable and fast enough

FUSETOOLS2-2520 - test with latest 4.8.3 productized
